### ISSUE TITLE
Plover shortcut breaks lookup shortcut

### ISSUE THREAD

**Issue by user202729** [fourshade/spectra_lexer#4]
In

https://github.com/fourshade/spectra_lexer/blob/56c9e6b4f2e94ee595c8046077ce99ef2d311038/spectra_lexer/app_plover.py#L28

the shortcut defined conflicts with Plover's built-in shortcut for lookup, thus breaks both.

**Comment by fourshade** [comment]
Interesting...you'd think one or the other would take precedence or throw an exception rather than breaking both silently. I don't think I've tried to access it by shortcut from Plover since I added that line...

Anyway, it's Ctrl+Shift+L now. When the lookup tool won't do, you need the "LOOKUP" tool. ;)
